#
# compile
#
nb_srcs  := 
nb_srcs  += $(wildcard nb_src/source/pmp??_*/*.py)

aux_srcs := 

users_csv := ldap_users_taulec.csv

feedback_class := pmp
include ../../../jupyter_tools/authoring/jupyter_tools.mk

# ../../../../taulec_env/user_scripts/tools/jupyter_tools.mk



