#
# compile
#
nb_srcs  := 
nb_srcs  += $(wildcard nb_src/source/pmp11_*/*.py)

users_csv := all_2022.csv

feedback_class := pmp
include ../../../../jupyter_tools/authoring/jupyter_tools.mk

# ../../../../taulec_env/user_scripts/tools/jupyter_tools.mk



